brokerAddress: tcp://zuckernas.ddns.net:1883
topics:
  alertManager:
    subscribe: airports/+
    publish: airports/alertManager/
influxdb:
  bucket: AirportMQTT
  org: ArchiD Team
  url: http://airportmqtt.ddns.net:8086
  subscribe: airports/+