brokerAddress: tcp://zuckernas.ddns.net:1883
port: 1883
sensors:
  - airportIATA: MRS
    geoIDInsee: 13054001
    clientID: wind_sensor_mrs
    transmissionFrequency: 10s
    qos: 1
  - airportIATA: LYS
    geoIDInsee: 69299001
    clientID: wind_sensor_lys
    transmissionFrequency: 10s
    qos: 1